modLoader = "kotlinforforgel"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "MATCH_VERSION"
description = '''${mod_description}'''
logoFile= "../../resources/logo.png"

[modproperties.betterwitchhuts]
    catalogueImageIcon="catalogue_icon.png"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kotlinforforge"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "etched"
mandatory = true
versionRange = "[3.0.4,3.1.0)"
ordering = "AFTER"
side = "BOTH"
